-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : dim. 20 nov. 2022 à 19:44
-- Version du serveur : 10.4.25-MariaDB
-- Version de PHP : 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `market`
--

-- --------------------------------------------------------

--
-- Structure de la table `product`
--

CREATE TABLE `product` (
  `ID` int(10) UNSIGNED NOT NULL,
  `Name` varchar(255) NOT NULL,
  `Producer` varchar(255) NOT NULL,
  `Price` double UNSIGNED NOT NULL,
  `NbPurchased` int(11) NOT NULL,
  `Evaluation` decimal(10,0) DEFAULT NULL,
  `Category` varchar(255) NOT NULL,
  `Description` text NOT NULL,
  `Caracteristics` text NOT NULL,
  `Stock` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `product`
--

INSERT INTO `product` (`ID`, `Name`, `Producer`, `Price`, `NbPurchased`, `Evaluation`, `Category`, `Description`, `Caracteristics`, `Stock`) VALUES
(1, 'Takamine-GD93CE', 'Takamine', 490, 0, '5', 'Acoustic', '<p class=\"paragraphe\">\r\nA distinguished acoustic/electric dreadnought guitar with a refined and contemporary look, the GD93CE features a solid top and special back construction, giving it an upscale feel and distinctive sound.\r\n</p>\r\n<p class=\"paragraphe\">\r\nFor players seeking stage-worthy features and an uncommon look, the GD93CE features a solid spruce top, rosewood sides and a beautiful three-piece rosewood/quilt maple back. The slim mahogany neck and 12”-radius bound rosewood fingerboard provide great feel and playability, while the onboard Takamine TK-40D preamp system gives you a built-in tuner, three-band EQ and gain controls, mid contour switch, notch filter and EQ bypass switch for the ultimate in versatility and sound quality.\r\n</p>\r\n<p class=\"paragraphe\">Other premium features include maple body, neck and headstock binding; dark wood rosette and body purfling; synthetic bone nut and split bridge saddle; rosewood headcap; abalone dot inlays; gold die-cast tuners with black buttons; and a beautiful gloss finish. Available in Natural.\r\n</p>', '<ul>\r\n<li>Build : Dreadnought with Cutaway</li>\r\n<li>Top : Solid Spruce</li>\r\n<li>Back and Sides : Walnut</li>\r\n<li>Neck : Mahogany</li>\r\n<li>Fretboard : Laurel</li>\r\n<li>Bridge : Laurel</li>\r\n<li>Number of Frets : 20</li>\r\n<li>Scale : 644 mm</li>\r\n<li>Nut Width : 43 mm</li>\r\n<li>Pickup System : Takamine TK-40D Preamp with Built-in-tuner</li>\r\n<li>Colour : Natural High Gloss</li>\r\n<li>Accessories : None</li>\r\n</ul>', 31),
(12, 'Dangelico-Premier', 'DAngelico', 899, 0, '3', 'Electric', '<p class=\"paragraphe\">\r\nD\'Angelico Premier is a fourteen-inch-wide double cutaway semi-hollow boasting warm and punchy tone. Sibling of the crowd favorite Premier DC, the Mini DC\'s undersized body, sleek headstock design and slim C-shape neck profile combine to create unprecedented comfort for every player.\r\n</p>\r\n<p class=\"paragraphe\">\r\nEquipped with Seymour Duncan Designed humbuckers and a standard three-way toggle switch, the Premier Mini DC offers rich, natural tone and sweet sustain by way of its centerblock semi-hollow design. Now available in Fiesta Red.\r\n</p>', '<ul>\r\n<li>Top: Mahogany</li>\r\n<li>Back and sides: Mahogany</li>\r\n<li>Neck: Maple</li>\r\n<li>Fretboard: Ovangkols</li>\r\n<li>Neck with satin natural finish</li>\r\n<li>Scale length: 628 mm</li>\r\n<li>Nut width: 43 mm</li>\r\n<li>Number of Frets</li>\r\n</ul>', 25),
(13, 'Epiphone-L-Studio', 'Epiphone', 333, 0, '4', 'Electroacoustic', '<p class=\"paragraphe\">\r\nThe Epiphone L-00 Studio Acoustic/Electric guitar is a direct descendent of Epiphone’s original line of flattops going back to the golden age of acoustic guitars in the 1930s.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe smaller \"parlor\" or \"blues box\" style acoustic guitar is favored by blues players of all eras for its compressed, woody tonal quality, short scale, and comfortable weight, which makes it ideal for fingerpicking or the bark of a bottleneck slide.\r\n</p>\r\n<p class=\"paragraphe\">\r\nNow featuring the Fishman® Sonitone™ soundhole preamp and Fishman® Sonicore™ pickup, the L-00 Studio Acoustic/Electric can now plug-in and be heard on any size stage with first class acoustic/electric sound.\r\n</p>\r\n<p class=\"paragraphe\">\r\n(Previously called EL-00 PRO)\r\n</p>', '<ul>\r\n<li>Material : Mahogany</li>\r\n<li>Profile : SlimTaper™ D</li>\r\n<li>Scale Length : 24.75\"</li>\r\n<li>Fingerboard Material : Indian Laurel</li>\r\n<li>Fingerboard Radius : 12\"</li>\r\n<li>Number of Frets : 19</li>\r\n<li>Finish : Nickel</li>\r\n<li>Tuner Plating : Nickel</li>\r\n<li>Body Shape : Acoustic</li>\r\n<li>Body Material : Select Mahogany</li>\r\n<li>Top : Solid Spruce</li>\r\n<li>Controls : Fishman® Sonitone™ Soundhole mounted Volume and Tone controls</li>\r\n</ul>', 5),
(14, 'ESP-SnakeByte', 'ESP', 1499, 0, '4', 'Electric', '<p class=paragraphe>\r\nLTD Signature Series Snakebyte features set-neck construction at 24.75\" scale with a mahogany body, a thin U-shaped three-piece mahogany neck, Macassar ebony fingerboard, 22 extra-jumbo frets, a TonePros locking TOM bridge and tailpiece, and James\' own EMG JH SET active pickups.\r\n</p>\r\n<p class=paragraphe>\r\nThe Snakebyte Camo is based on a camouflage pattern created by high-performance hunting gear manufacturer KUIU, a design chosen by Hetfield.\r\n</p>\r\n<p class=paragraphe>\r\nThe LTD Snakebyte Camo includes a matching special hardshell case. A portion of the proceeds from each Snakebyte Camo goes to Metallica’s All Within My Hands Foundation, a non-profit, philanthropic organization dedicated to creating sustainable communities by supporting workforce education, the fight against hunger, and other critical local services.\r\n</p>', '<ul>\r\n<li>Scale : 24.75\"</li>\r\n<li>Body : Mahogany</li>\r\n<li>Neck : Mahogany</li>\r\n<li>Fingerboard : Macassar Ebony</li>\r\n<li>Fingerboard Radius : 350 mm</li>\r\n<li>Finish : Kuiu Camo Satin</li>\r\n<li>Nut Width : 42 mm</li>\r\n<li>Nut Type : Molded</li>\r\n<li>Neck Contour : Thin U</li>\r\n<li>Number of Frets and Type : 22 XJ</li>\r\n<li>Hardware Color : Black</li>\r\n<li>Tuners : LTD Locking</li>\r\n<li>Bridge : Tonepros Locking TOM & Tailpiece</li>\r\n<li>Neck : PUEMG JH \"HET\" SET</li>\r\n<li>Bridge : PUEMG JH \"HET\" SET</li>\r\n</ul>', 40),
(15, 'Fender-Troy-Jazzmaster', 'Fender', 1499, 0, '5', 'Electric', '<p class=\"paragraphe\">\r\nYou\'ve heard the musical textures and atmospheres of Troy Van Leeuwen in some of the most famous and avant-garde alternative heavy rock bands. From Failure to A Perfect Circle, including Queens of the Stone Age, Eagles of Death Metal and Puscifer to name a few, Van Leeuwen\'s talent as a multi-instrumentalist brings color and power to the most popular rock and the most creative of the last three decades.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe Troy Van Leeuwen Jazzmaster, with its personalized elements such as the custom colored finishes, the special switching system and the modified bridge, is as unique as the sound it produces with his guitar.\r\n</p>', '<ul>\r\n<li>Body : Alder</li>\r\n<li>Body finish : Gloss Polyester</li>\r\n<li>Body shape : Jazzmaster</li>\r\n<li>Knobs : White \"Witch Hat\"</li>\r\n<li>Fingerboard : Bound Rosewood</li>\r\n<li>Hardware : Nickel/Chrome</li>\r\n<li>Pickguard : Tortoiseshell</li>\r\n<li>Inlays : White Pearloid Block</li>\r\n<li>Nech finish : Gloss Urethane</li>\r\n<li>Orientation : Right-Hand</li>\r\n<li>Nut : Synthetic Bone</li>\r\n<li>Bridge : Jazzmaster Bridge with Nickel-Plated Brass Mustang Saddles and Vintage Style \"Floating\" Tremolo Tailpiece</li>\r\n<li>Tuning machines : Vintage-Style</li>\r\n<li>Case/ Gigbag : Deluxe Hardshell</li>\r\n<li>Radius : 7.25\" (184.1 mm)</li>\r\n<li>Frets Syze : Vintage Style</li>\r\n<li>Neck Material : Maple</li>\r\n<li>Refinement Neck Material : Maple</li>\r\n<li>Neck profil : \"C\" Shape</li>\r\n<li>Refinement Neck Shape : C Shape</li>\r\n<li>Number of Frets : 21</li>\r\n</ul>', 1),
(16, 'Fender-Vintera', 'Fender', 1050, 0, '4', 'Electric', '<p class=\"paragraphe\">\r\nFor musicians who want to rediscover the style and sound of Fender\'s Golden Age, we have created the Vintera \'60s Jazzmaster.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThis guitar features all the prized elements of the decade - including the neck profile and feel of vintage models, but also reconfigured pickups. It delivers all of the characteristic bite and twang that made the Jazzmaster a true legend.\r\n</p>\r\n<p class=\"paragraphe\">\r\nWe have modified the pair of Jazzmaster single-coil pickups; their behavior is closer to that of the original models and they offer an authentic vintage sound.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe warmth and smoothness of the neck pickup is offset by the shine and bite of the model in the bridge position.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe \'Mid 60s C\' profile neck is finished with an elegant painted head and topped with a 7.25 \"(184mm) radius maple fingerboard with 21 vintage-style frets, ensuring a classic feel. A Jazzmaster bridge from vintage style with a floating vibrato and also vintage style tuners give the instrument a vintage aesthetic while ensuring unparalleled performance and perfect tuning stability.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThis guitar finally includes the classic Lead / Rhythm circuit , chrome hardware and a four-screw neck mounting plate. A deluxe gig bag is included.\r\n</p>', '<ul>\r\n<li>Body : Alder</li>\r\n<li>Body finish : Gloss Polyester</li>\r\n<li>Body Binding : None</li>\r\n<li>Body shape : Jazzmaster</li>\r\n<li>Knobs : Aged White</li>\r\n<li>Fingerboard : Pau Ferro</li>\r\n<li>Hardware : Nickel/Chrome</li>\r\n<li>Pickguard : Tortoiseshell</li>\r\n<li>Inlays : White Dot</li>\r\n<li>Nech finish : Gloss Urethane</li>\r\n<li>Neck pickup : Vintage-Style \'60s Single-Coil Jazzmaster</li>\r\n<li>Orientation : Right-Hand</li>\r\n<li>Nut : Synthetic Bone</li>\r\n<li>Tuning machines : Vintage-Style\r\n<li>Case/ gigbag : Included: Deluxe Gig Bag</li>\r\n<li>Radius : 7.25\" (184.1 mm)</li>\r\n<li>Neck material : Maple</li>\r\n<li>Neck profil : Mid \'60s \"C\"</li>\r\n<li>Number of Frets : 21</li>\r\n</ul>', 0),
(17, 'Gibson-Custom-EDS-DoubleNeck', 'Gibson', 1449, 0, '5', 'Electric', '<p class=\"paragraphe\">\r\nThe Gibson EDS-1275 is an iconic design that has captured the imagination of fans and players for generations.\r\n</p>', '<ul>\r\n<li>Profile : SlimTaper C</li>\r\n<li>Scale Length : 628.65 mm</li>\r\n<li>Fret Count : 20</li>\r\n<li>Frets : Authentic Medium-Jumbo</li>\r\n<li>Nut Material : Corian</li>\r\n<li>Nut Width : 42.85 mm</li>\r\n<li>Tuning Machines : Gibson Deluxe, Double Ring</li>\r\n<li>Switch Tip : Black</li>\r\n<li>Control Covers : Black</li>\r\n<li>Strap Buttons : Aluminum</li>\r\n<li>Mounting Rings : Black</li>\r\n<li>Pickup Covers : Nickel</li>\r\n</ul>', 36),
(18, 'Gibson-SG', 'Gibson', 5999, 0, '5', 'Electric', '<p class=\"paragraphe\">\r\nBack in Black…and Heritage Cherry!\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe Gibson SG Standard rocks the classic looks and features associated with the late 60\'s style SG models sought after by many.\r\n</p>\r\n<p class=\"paragraphe\">\r\nA rounded profile mahogany neck, bound rosewood fingerboard, long tenon 19th fret neck joint, and a solid mahogany body provide the backbone for singing sustain. The 490R and 490T Alnico II pickups provide the power to drive. A black, 5-ply, full-face pickguard set this SG Standard apart from others... a truly versatile classic.\r\n</p>', '<ul>\r\n<li>Material : Mahogany</li>\r\n<li>Profile : Rounded</li>\r\n<li>Scale Length : 24.75\"</li>\r\n<li>Fingerboard Material : Rosewood</li>\r\n<li>Fingerboard Radius : 12\"</li>\r\n<li>Number of Frets : 22</li>\r\n<li>Frets : Medium Jumbo</li>\r\n<li>Nut Material : Graph Tech</li>\r\n<li>Nut Width : 1.695\"</li>\r\n<li>Inlays : Acrylic Trapezoids</li>\r\n<li>Body Material : Mahogany</li>\r\n<li>Finish : Gloss Nitrocellulose Lacquer</li>\r\n<li> Hardware Finish : Chrome</li>\r\n<li>Bridge : Aluminum Nashville Tune-O-Matic</li>\r\n<li>Tuning Machines : Grover Rotomatics w/ Kidney Buttons</li>\r\n<li>Control Knobs : Black Top Hats with Silver Reflector</li>\r\n<li>Switch Tip : Cream</li>\r\n<li>Switchwasher : Black</li>\r\n</ul>', 1),
(19, 'Gretsch-12-FalconRanger', 'Gretsch', 609, 0, '0', 'Electroacoustic', '<p class=\"paragraphe\">\r\nThe G5022CWFE-12 Rancher Falcon Jumbo 12-String gives you lavishly full 12-string tone with full-on Gretsch Falcon style, sparkling gilded appointments and onboard electronics for peerless amplified tone.\r\n</p>\r\n<p class=\"paragraphe\">\r\nIts jumbo cutaway body is finished in gloss white, with dazzling gold-sparkle binding on the top, back, sound hole, fingerboard and headstock.\r\n</p>', '<ul>\r\n<li>Body : Laminated Maple Back and Sides</li>\r\n<li>Body finish : Gloss Polyester</li>\r\n<li>Body Top : Solid Spruce</li>\r\n<li>Body shape : Jumbo</li>\r\n<li>Body Back : Laminated Maple</li>\r\n<li>Body Sides : Laminated Maple</li>\r\n<li>Fingerboard : Rosewood with Gold Sparkle Binding</li>\r\n<li>Hardware : Gold-Plated</li>\r\n<li>Neck finish : Gloss Polyester</li>\r\n<li>Headstock : Falcon Style</li>\r\n<li>Special Electronics : Fishman Isys III System with Active Onboard Preamp and Tuner</li>\r\n<li>Orientation : Right-Hand</li>\r\n<li>Nut : Synthetic Bone</li>\r\n<li>Bridge : Rosewood with Compensated Synthetic Bone Saddle</li>\r\n<li>Tuning machines : Deluxe Die-Cast</li>\r\n<li>Uniques features : V-Shaped Matching White Painted Falcon Headstock with Gold-Sparkle Inlaid Gretsch Vertical Winged Logo, Traditional Gretsch Rancher \"Triangular\" Sound Hole, Gold Sparkle Bound Body Neck and Headstock with B/W/B/W Purfling, Gold Sparkle Heel Cap, Synthetic Bone Nut, Knurled Strap Retainer Knobs, Adjustable Truss Rod with Headstock Adjustment</li>\r\n<li>Frets syze : Vintage Style</li>\r\n<li>Neck material : Mahogany</li>\r\n<li>Refinement Neck Material : Mahogany</li>\r\n<li>Number of Frets : 21</li>\r\n</ul>', 70),
(20, 'Harley-Benton-Custom-CL', 'Harley Benton', 148, 0, '1', 'Electroacoustic', '<p class=\"paragraphe\">\r\nDepth, precision, power and great looks – this Custom Line dreadnought model has it all. Let’s start off with the tone woods: a solid sitka pruce top combines here with a gorgeous walnut body and a mahogany neck loaded with a pau ferro fretboard, all harmonising together perfectly for a wonderfully balanced sound.\r\n</p>\r\n<p class=\"paragraphe\">\r\nAttractive white binding, mother-of-pearl inlays and gold-coloured tuners round off the stylish aesthetics on this special guitar. Outside the living room or studio, the integrated Fishman preamp and tuner turn this guitar into a reliable gigging guitar too. Whether as your first dreadnought or a reliable back-up instrument, the CLD-41SE WN has you covered.\r\n</p>', '<ul>\r\n<li>Top : Solid Sitka Spruce</li>\r\n<li>Body : Walnut</li>\r\n<li>Mahogany neck</li>\r\n<li>Pau Ferro fretboard</li>\r\n<li>Binding : Abalone</li>\r\n<li>Neck Profile : Modified Oval C</li>\r\n<li>Scale: 643 mm</li>\r\n<li>Nut Width: 43 mm</li>\r\n<li>Nut : Bone</li>\r\n<li>Number of Frets : 20</li>\r\n<li>Pickup System: Fishman Presys-II preamp system with built-in tuner</li>\r\n<li>Color: Natural matte</li>\r\n</ul>', 0),
(21, 'Harley-Benton-D120', 'Harley Benton', 89, 0, '1', 'Electroacoustic', '<p class=\"paragraphe\">\r\nThe D-120NT is a purebred dreadnought crafted from classic tone woods that ensure powerful volume and a rich bass range. The back, sides and neck are made of mahogany; traditional X-bracing was used for the spruce top. The modern C-shape neck is slightly narrower, guaranteeing a comfortable playing feel.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThis elegant instrument is clothed in a sumptuous natural high-gloss finish - and its detailed, versatile sound is a treat for the ears.\r\n</p>', '<ul>\r\n<li>Body shape: Dreadnought</li>\r\n<li>Top: Spruce</li>\r\n<li>Body and Sides: Mahogany</li>\r\n<li>Neck: Mahogany</li>\r\n<li>Scale: 650 mm</li>\r\n<li> Number of Frets : 20</li>\r\n<li>Nut Width: 42.5 mm</li>\r\n<li>Color: Natural, high gloss</li>\r\n</ul>', 10),
(22, 'Harley-Benton-TE52', 'Harley Benton', 165, 0, '2', 'Electric', '<p class=\"paraphe\">\r\nIt\'s time for you to leave your musical mark deep in the history of rock with this mind-blowing Harley Benton TE52.\r\n</p>\r\n<p class=\"paragraphe\">\r\nIts looks and character will take you straight to the country of the rock legends; you won\'t regret your investment.\r\n</p>', '<ul>\r\n<li>Body: Basswood</li>\r\n<li>Neck: Canadian maple</li>\r\n<li>Fingerboard: Rosewood</li>\r\n<li>Scale length: 648mm</li>\r\n<li>Pickups: 2 single coils</li>\r\n<li>Controls: 3-way switch</li>\r\n<li>Bridge: Vintage</li>\r\n<li>Pickguard: Black</li>\r\n<li>Tuners: Lubricated gear in sealed housing</li>\r\n<li>Finish: Blonde</li>\r\n</ul>', 20),
(23, 'LAG-Tramontane', 'LAG', 539, 0, '5', 'Electroacoustic', '<p class=\"paragraphe\">\r\nThanks to the khaya of its body, a wood with excellent stability, and its red cedar soundboard with singular acoustic properties, the T118 largely dominate the competition in their price range. Guitars with warm and soft tones that assert themselves as well on small and slim auditoriums as on the dreadnought, powerful and precise.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThey are available in several finishes, with or without cutaway. The Tramontane of this 118 series are available in several finishes, with or without cutaway, to satisfy all demanding musicians in search of a versatile instrument.\r\n</p>', '<ul>\r\n<li>Table : Solid Red Cedar</li>\r\n<li>Back & Sides: Khaya</li>\r\n<li>Finish : Shiny</li>\r\n<li>Bridge : Brownwood</li>\r\n<li>Handle : Khaya</li>\r\n<li>Finish : Satin</li>\r\n<li>Adjustment Rod : Two-Way</li>\r\n<li>Fingerboard : Brownwood</li>\r\n<li>Number of Frets : 20 - Silver Nickel</li>\r\n<li>Scale : 650 mm</li>\r\n<li>Head nut : Black Graphite</li>\r\n<li>Property of Matthieu Dartois, value increased proportionaly</li>\r\n>/ul>', 1),
(24, 'Larry-Carlton-T7', 'Larry Carlton', 589, 0, '5', 'Electric', '<p class=\"paragraphe\">\r\nWith the addition of flamed aesthetics, Sire T7 FM is packaged not only to hold a great sound versatility but also a great personality.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe latest T-style electric guitar is built for thrilling and remarkable performances.\r\nThe Larry Carlton-approved body shape, aesthetics, build, hardware and electronics make up the old-style but for all-time Sire T7 FM.\r\n<p>', '<ul>\r\n<li>Neck : Solid Roasted Maple</li>\r\n<li>Scale: 25\'5 ”</li>\r\n<li> Fingerboard : Solid Roasted Maple (Radius: 9\'5 ”)</li>\r\n<li>Number of Frets: 22 Medium Jumbo</li>\r\n<li>Nut: 42mm</li>\r\n<li>Binding: Abalone Inlays</li>\r\n<li>Bridge: S7 2-point tremolo (Stainless Steel Block)</li>\r\nMechanical: High quality cover (Chrome)\r\n<li>Pickguard: White Mother-of-Pearl\r\nAntique White Finish</li>\r\n</ul>', 3),
(25, 'Lava-Music-Me', 'Lava-Music', 1400, 0, '5', 'Electroacoustic', '<p class=\"paragraphe\">\r\nIntuitive. Creative. Powerful. This Acoustic-electric is designed to be thebest companion of your musical adventure. With a multi-touchdisplay, the HILAVA OS and incredible apps, LAVA ME 3 will reinvent the way you make music.\r\n</p>', '<ul>\r\n<li>Design : Dreadnought</li>\r\n<li>Construction : Dovetail</li>\r\n<li>Top : Solid Sitka Spruce</li>\r\n<li>Body : AirSonic 2 carbon fiber with Super AirSonic carbon fiber top</li>\r\n<li>Number of Frets : 18</li>\r\n<li>Tuners : Lava-designed ultra light aluminum.18:1 ratio</li>\r\n<li>Controls : Volume wheel and on/off/sleep/ wake button inside sound port. 3.5” multitouch screen on top side with status, menu and app icons</li>\r\n<li>Connectivity : Wi-fi, Bluetooth, ¼” output jack, USB-C jack for charging, contact charging available via Space Charging Dock (sold separately; $149 for 38”, $129 for 36”)</li>\r\n<li>Power : 8,000 mAh/3.8V lithium-ion battery (up to nine hours of playing time), USB-C to USB-C and USB-C to USB-A cables provided, 15W USB-C charging adaptor not included</li>\r\n<li>Weight : 4.96 lbs</li>\r\n</ul>', 1),
(26, 'LTD-EII-Eclipse', 'LTD', 979, 0, '5', 'Electric', '<p class=\"paragraphe\">\r\nThe EC-256 black benefits from all the technical control of the employees of the LTD factory. With this powerful and versatile guitar, bang the crowd!\r\n</p>\r\n<p class=\"paragraphe\">\r\nA whole new look redesigned in 2017, the LTD EC-256 takes up most of the coolest aspects of the high-end Eclipse models! Its classic shape is perfect for all styles and musical genres and it must be admitted that the addition of multiple bindings on the body and head reinforces this premium side.\r\n</p>\r\n<p class=\"paragraphe\">\r\nA guitar at the top! The EC-256 features a mahogany body, a comfortable three-part U-shaped handle of the same essence, a rosewood fingerboard with flag inlay and 22 extra-jumbo frets. To sublimate everything, this guitar has two pickups ESP Designed LH-150.\r\n</p>\r\n<p class=\"paragraphe\">\r\nOne of the great strengths of LTD is also to have an incredible propensity to revisit and totally update the myths of the guitar: chamfers and cutaway scored for a modern line and humbuckers ESP pickups, Seymour Duncan or EMG for a big sound very current. The EC series has everything for modern guitarists!\r\n</p>', '<ul>\r\n<li>Body : Mahogany</li>\r\n<li>Hardware : Gold</li>\r\n<li>Format: Les Paul</li>\r\n<li>Body: Mahogany</li>\r\n<li>Handle: Mahogany</li>\r\n<li>Fingerboard: Rosewood</li>\r\n<li>Number of Frets: 22</li>\r\n</ul>', 12),
(27, 'Solar-V16', 'Solar', 799, 0, '4', 'Electric', '<p class=\"paragraphe\">\r\nThis Type V1.6 six-string guitar will set you apart from everyone else. With its distinctive, stealth looks and feature set, this guitar is a precise, professional instrument suitable for both stage and studio work. The reliable Floyd Rose 1000, made of hardened steel combined with an oversized block, offers increased sustain and resonance while all tremolo springs are mechanically muted.\r\n</p>\r\n<p class=\"paragraphe\">\r\nIt also features Duncan Solar pickups that provide a full spectrum of tonal options, from organic clean to heavily overdriven, all with fluid sustain and maximum clarity. The Type V1.6 features a set-thru neck/body joint design with 25.5” scale, mahogany body with flame maple veneer top, a fast, thin, comfortable maple neck, an ebony fingerboard with 24 super-jumbo stainless steel frets and Luminlay ‘glow in the dark’ side dots for stage use.\r\n</p>\r\n<p class=\"paragraphe\">\r\nLoaded with Solar 18:1 locking tuners, locking nut, 3-way toggle pickup switching with push-pull and full access neck. Available in flame lime burst matte finish, it also includes a Solar Type V deluxe gig bag.\r\n</p>', '<ul>\r\n<li>Construction: Set-Neck</li>\r\n<li>Scale : 24.75\"</li>\r\n<li>Body : Mahogany</li>\r\n<li>Neck : Mahogany</li>\r\n<li>Fingerboard : Macassa Ebony</li>\r\n<li>Fingerboard Radius : 350 mm</li>\r\n<li>Finish : Kuiu Camo Satin</li>\r\n<li>Nut Width : 42 mm</li>\r\n<li>Nut Type : Molded</li>\r\n<li>Neck Contour : Thin U</li>\r\n<li>Frets/Type : 22 XJ</li>\r\n<li>Hardware Color : Black</li>\r\n<li>Strap Button : Standard</li>\r\n</ul>', 80),
(28, 'Squier-Affinity', 'Squier', 235, 0, '1', 'Electric', '<p class=\"paragraphe\">\r\nA superb gateway into the time-honored Fender family, the Squier Affinity Series Stratocaster delivers legendary design and quintessential tone for today\'s aspiring guitar hero. This Strat features several player-friendly refinements such as a thin and lightweight body, a slim and comfortable \"C\"-shaped neck profile, a 2-point tremolo bridge for superior tremolo action and sealed die-cast tuning machines with split shafts for smooth, accurate tuning and easy restringing.\r\n</p>\r\n<p class=\"paragraphe\">\r\nLoaded with a trio of Squier single-coil Strat pickups with 5-way switching for genre-defying sonic variety, this model is ready to accompany any player at any stage.\r\n</p>', '<ul>\r\n<li>Body : Poplar</li>\r\n<li>Body Finish : Gloss Polyurethane</li>\r\n<li>Body Shape : Stratocaster</li>\r\n<li>Fingerboard : Maple</li>\r\n<li>Hardware : Chrome</li>\r\n<li>Neck Finish : Satin Urethane with Gloss Urethane Headstock Face</li>\r\n<li>Neck Construction : Bolt-On</li>\r\n<li>Nut : Synthetic Bone</li>\r\n<li>Radius : 9.5\" (241 mm)</li>\r\n<li>Refinement Fingerboard Radius : Modern</li>\r\n<li>Frets Syze : Medium Jumbo</li>\r\n<li>Number of Frets : 21</li>\r\n</ul>', 3),
(29, 'Squier-ST', 'Squier', 495, 0, '3', 'Electric', '<p class=\"paragraphe\">\r\nThe first instruments to bear the Squier name were introduced in 1982, answering the call for genuine Fender designs at accessible prices. The Squier 40th Anniversary collection celebrates the 40-year journey of Fender’s entry-level brand with special editions of the Telecaster, Stratocaster, Jazzmaster, Precision Bass, and Jazz Bass, all available in Gold Edition and Vintage Edition variants.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe Squier 40th Anniversary Stratocaster, Vintage Edition is a soulful tribute model trimmed with a collection of classic features for the retro-minded Squier enthusiast. Featuring aged chrome hardware, an anodized aluminum pickguard, a vintage-tinted maple neck, an engraved anniversary neck plate and satin finish throughout, this Strat honors the heritage of the Squier catalog and its ancestry.\r\n</p>\r\n<p class=\"paragraphe\">\r\nPlayer-friendly refinements of this commemorative model include a slim and comfortable “C”-shaped neck profile for an easy playing feel, vintage-style tuning machines and 6-saddle synchronized tremolo bridge for authentic performance and style, and Fender-Designed single-coil pickups with alnico 5 magnets for familiar Strat tone.\r\n</p>', '<ul>\r\n<li>Body : Nyatoh</li>\r\n<li>Body Finish : Satin Urethane</li>\r\n<li>Body Shape : Stratocaster</li>\r\nControl Buttons : Aged White Plastic</li>\r\n<li>Fingerboard : Maple</li>\r\n<li>Hardware Finish : Aged Chrome</li>\r\n<li>Fingerboard Insert : Black Dot</li>\r\n<li>Neck Finish : Tinted Satin Urethane</li>\r\n<li>Neck Construction : Bolt-On</li>\r\n<li>Neck Head : Stratocaster</li>\r\n</ul>', 6),
(30, 'Steinberg-GT-Pro', 'Steinberg', 311, 0, '0', 'Electric', '<p class=\"paragraphe\">\r\nSteinberger presents the new GT-PRO Deluxe Outfit, the Ultimate Travel Guitar™ featuring the revolutionary Steinberger body design in Black, Frost Blue, Hot Rod Red, Hot Rod Yellow, White, and Yin Yang Gloss finishes.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe Steinberger GT-PRO includes the patented 40:1 Ratio Direct-Pull tuning and locking R-Trem™ tremolo systems plus a 3-pc Hard Maple neck with adjustable truss rod for an incredible sounding guitar that’s practically indestructible. The GT-PRO Deluxe Outfit is part of the new Steinberger Spirit Collection and includes a deluxe gigbag.\r\n</p>', '<ul>\r\n<li>Finish: Gloss</li>\r\n<li>Neck Material: 3-pc Hard Maple</li>\r\n<li>Body Top: AAA Quilt Maple Veneer</li>\r\n<li>Body Material : Basswood</li>\r\n<li>Neck Shape : 1960\'s SlimTaper™; D Profile</li>\r\n<li>Fingerboard Material : Engineered Hardwood</li>\r\n<li>Fingerboard Radius : 14\"</li>\r\n<li>Number of Frets : 24 Medium-Jumbo</li>\r\n<li>Scale Length : 25.5\"</li>\r\n</ul>', 40),
(31, 'Sterling-Cutlass-TE', 'Sterling', 394, 0, '1', 'Electric', '<p class=\"paragraphe\">\r\nThe Squier Contemporary Telecaster RH brings modern elements and a bold aesthetic to a legendary Fender model to satisfy the most demanding and daring guitarists.\r\n</p>\r\n<p class=\"paragraphe\">\r\nAt the heart of this guitar are a Rail SQR humbucker pickup in the bridge position (RH = Rail Humbucker) and a Squier SQR Atomic humbucker in the neck position to offer a wide variety of unique tones, and without generating any hiss.\r\n</p>\r\n<p class=\"paragraphe\">\r\nThe roasted maple neck was chosen for its exceptional tone and stability; in addition, its sculpted heel gives you easy access to the 22nd fret.\r\n</p>', '<ul>\r\n<li>Hardware : Black</li>\r\n<li>Neck finish : Satin Urethane with Gloss Urethane Headstock Face</li>\r\n<li>Neck Construction : Bolt-On</li>\r\n<li>Headstock : Matching Painted with Chrome Logo</li>\r\n<li>Orientation : Right-Hand</li>\r\n<li>Nut : Graphite</li>\r\n</ul>', 20),
(32, 'Taylor-BabyTaylor', 'Taylor', 379, 0, '4', 'Acoustic', '<p class=\"paragraphe>\r\nThe mahogany-top version of the Baby Taylor will yield a slightly darker, earthier tone than its spruce top sibling. The pint-size Dreadnought was originally inspired by a desire to provide a smaller, starter-size guitar for kids and a legitimate musical companion for travelers, but players have since adapted it for their needs in all sorts of creative ways, from high-stringing it to setting it up to play lap slide, to embracing alternate tunings that add unique acoustic flavors to recordings.\r\n</p>\r\n<p class=\"paragraphe>\r\nThis model also comes equipped with the Expression System Baby? (ES-B) pickup, which incorporates piezo design elements from the Taylor ES2. The pickup is powered by an onboard preamp with a built-in digital chromatic tuner. The preamp/tuner unit features an LED display for tuning and low battery indication, along with Tone and Volume controls.\r\n</p>', '<ul>\r\n<li>Specialty : Travel/Small Body</li>\r\n<li>Shape : Baby</li>\r\n<li>Top Wood : Tropical Mahogany</li>\r\n<li>Body Wood : Layered Sapele</li>\r\n<li>Body Length : 15-3/4\"</li>\r\n<li>Body Width : 12-1/2\"</li>\r\n<li>Body Depth : 3-3/8\"</li>\r\n<li>Scale Length : 22-3/4\"</li>\r\n<li>Nut & Saddle : Nubone Nut, Micarta Saddle</li>\r\n<li>Number of Frets : 19</li>\r\n<li>Tuners : Die-Cast Chrome</li>\r\n<li>Case : Gig Bag</li>\r\n<li>Top Finish : Varnish</li>\r\n<li>Rosette Size : Single Ring</li>\r\n<li>Back/Sides Finish : Varnish</li>\r\n<li>Rosette Material : Plastic</li>\r\n<li>Neck Wood : Mahogany</li>\r\n<li>Fretboard Wood : West African Ebony</li>\r\n<li>Neck Finish : Varnish</li>\r\n<li>Headstock Overlay : Copafera</li>\r\n<li>Buttons : Chrome</li>\r\n</ul>', 0);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `product`
--
ALTER TABLE `product`
  MODIFY `ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
